spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: book
    password: book
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
