spring:
  application:
    name: demo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book
      username: book
      password: book
  flyway:
    baseline-on-migrate: true
    enabled: false

